name: Brock Butler
favicon: null
layout_spectrum: 0.50193
typography_spectrum: 0.53083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e1211'
    - '#f1bc92'
    - '#fbfbfb'
    - '#848a96'
    - '#46522e'
  brandStrength: 0.8186306485440582
  lightness: 0.8810298827011138
  saturation: 0.14601993886753917
  rhythmicContrast: 0.8270730332005769
purpose: []
